[macOS] Add unxip for macOS13
actions/runner-images pull request #10908
Opened 2024-11-06 03:57 UTC by sarathrajsrinivasan

# Description
Add unxip for macOS13 and macOS13 arm images.

#### Related issue:

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

2024-11-06 10:58 UTC, erik-bershel requested changes

2024-11-06 14:37 UTC, sarathrajsrinivasan commented on images/macos/scripts/docs-gen/SoftwareReport.Common.psm1
> +    $unxipVersion = ($Version -split " ")[1]
Updated.

2024-11-06 14:38 UTC, sarathrajsrinivasan commented on images/macos/scripts/build/install-unxip.sh
> +echo "unxip installation completed."
Updated.

2024-11-06 14:38 UTC, sarathrajsrinivasan commented on images/macos/templates/macOS-13.arm64.anka.pkr.hcl
> +      "${path.root}/../scripts/build/install-unxip.sh"
Done

2024-11-06 14:52 UTC, Alexey-Ayupov approved these changes

2024-11-06 16:06 UTC, Alexey-Ayupov approved these changes

2024-11-06 22:24 UTC, erik-bershel approved these changes

2024-11-07 05:28 UTC, susmitamane approved these changes

2024-11-07 05:40 UTC, aartis17 approved these changes

2024-11-07 06:17 UTC, prasanjitsahoo approved these changes

2024-11-07 06:17 UTC, merged