[windows] Don't fail Windows Update test if an update failed but later succeeded
actions/runner-images pull request #11253
Opened 2024-12-31 00:13 UTC by AtOMiCNebula

# Description
Bug fix

I've been trying to build the Windows Server 2025 image this month, and eight of nine attempts to build have failed due to Windows Update failures (the ninth was a fluke failure during VS installation). I kept the OS disk and debugged into it, and the issue was that the "Windows Malicious Software Removal Tool x64 - v5.130 (KB890830)" update was failing due to the machine being rebooted. It appears the install was starting around the time `Install-PowerShellCore.ps1` was running. On a hunch, I tried updating the PS installer to set `ENABLE_MU=0`/`USE_MU=0` but the failures didn't go away.

Broken Test Output (note duplicate entries for MSRT):
```yaml
azure-arm.image: Describing Windows Updates
azure-arm.image:   [+] WindowsUpdateDone.txt should exist 5ms (2ms|3ms)
azure-arm.image:   [+] 2024-11 Cumulative Update for .NET Framework 3.5 and 4.8.1 for Microsoft server operating system version 24H2 for x64 (KB5045934) 57ms (56ms|1ms)
azure-arm.image:   [+] Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.421.1098.0) - Current Channel (Broad) 4ms (2ms|2ms)
azure-arm.image:   [+] Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.421.1101.0) - Current Channel (Broad) 2ms (1ms|1ms)
azure-arm.image:   [+] Security Update for Microsoft OLE DB Driver for SQL Server (KB5040711) 2ms (1ms|1ms)
azure-arm.image:   [+] Update for Microsoft Defender Antivirus antimalware platform - KB4052623 (Version 4.18.24090.11) - Current Channel (Broad) 2ms (1ms|1ms)
azure-arm.image:   [-] Windows Malicious Software Removal Tool x64 - v5.130 (KB890830) 175ms (173ms|2ms)
azure-arm.image:    Expected collection 'Installed' to contain 'Failed', but it was not found.
azure-arm.image:    at $State | Should -BeIn $expect, C:\image\tests\WindowsFeatures.Tests.ps1:76
azure-arm.image:    at <ScriptBlock>, C:\image\tests\WindowsFeatures.Tests.ps1:76
azure-arm.image:   [+] Windows Malicious Software Removal Tool x64 - v5.130 (KB890830) 3ms (2ms|1ms)
```

To address this, I've updated the WU logic to ignore an earlier failure for a given update if it is followed by a successful attempt.

I don't know if there is a larger issue here...should WU be running in the background at this point? I only encountered this issue on the WS2025 image, and have also been building WS2022 and WS2019 a bunch without issue, so maybe something's still off with the new image?

#### Related issue:
I haven't created one, but can if you'd like me to.

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [X] Changes are tested and related VM images are successfully generated

2024-12-31 03:02 UTC, bearycool11 commented
here, let me help you finish this, as this adds onto @IntelligenceQ's stub work from 3 days ago/10 minutes ago.

Look at  my version as a prototype for this repo 
https://github.com/bearycool11/pmll_blockchain/blob/main/.devcontainer/internal.windows-2025.json

2024-12-31 03:06 UTC, bearycool11 commented on images/windows/scripts/tests/WindowsFeatures.Tests.ps1
> -    $testCases = Get-WindowsUpdateStates | Sort-Object Title | ForEach-Object {
oh I see, yeah this jSON is going to be really long I got you one second.
[internal.windows-2025.json](https://github.com/user-attachments/files/18279003/internal.windows-2025.json)

2024-12-31 03:13 UTC, bearycool11 approved these changes
{
  "NodeType": "HeaderNode",
  "Title": "Windows Server 2025",
  "Children": [
    {
      "NodeType": "ToolVersionNode",
      "ToolName": "OS Version:",
      "Version": "10.0.26100 Build 2605"
    },
    {
      "NodeType": "ToolVersionNode",
      "ToolName": "Image Version:",
      "Version": "20241215.1.0"
    },
    {
      "NodeType": "HeaderNode",
      "Title": "Windows updates",
      "Children": [
        {
          "NodeType": "ToolVersionNode",
          "ToolName": "Update Title",
          "Version": "Some Update",
          "TimeCreated": "2024-12-30T12:34:56Z"
        },
        {
          "NodeType": "ToolVersionNode",
          "ToolName": "Another Update",
          "Version": "Another Update Version",
          "TimeCreated": "2024-12-30T12:34:56Z"
        }
      ]
    },
    {
      "NodeType": "HeaderNode",
      "Title": "Windows features",
      "Children": {
        "NodeType": "ToolVersionNode",
        "ToolName": "Windows Subsystem for Linux (WSLv1):",
        "Version": "Enabled"
      }
    },
    {
      "NodeType": "HeaderNode",
      "Title": "Installed Software",
      "Children": [
        {
          "NodeType": "HeaderNode",
          "Title": "Language and Runtime",
          "Children": [
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Bash",
              "Version": "5.2.37(1)-release"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Go",
              "Version": "1.23.4"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Julia",
              "Version": "1.10.5"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Kotlin",
              "Version": "2.1.0"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "LLVM",
              "Version": "19.1.5"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Node",
              "Version": "22.12.0"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Perl",
              "Version": "5.40.0"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "PHP",
              "Version": "8.3.14"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Python",
              "Version": "3.9.13"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Ruby",
              "Version": "3.3.6"
            }
          ]
        },
        {
          "NodeType": "HeaderNode",
          "Title": "Package Management",
          "Children": [
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Chocolatey",
              "Version": "2.4.1"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Composer",
              "Version": "2.8.4"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Helm",
              "Version": "3.16.2"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Miniconda",
              "Version": "24.9.2 (pre-installed on the image but not added to PATH)"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "NPM",
              "Version": "10.9.0"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "NuGet",
              "Version": "6.12.1.1"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "pip",
              "Version": "24.3.1 (python 3.9)"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Pipx",
              "Version": "1.7.1"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "RubyGems",
              "Version": "3.5.22"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Vcpkg",
              "Version": "(build from commit c26eabb23)"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Yarn",
              "Version": "1.22.22"
            },
            {
              "NodeType": "HeaderNode",
              "Title": "Environment variables",
              "Children": {
                "NodeType": "TableNode",
                "Headers": "Name|Value",
                "Rows": [
                  "VCPKG_INSTALLATION_ROOT|C:\\vcpkg",
                  "CONDA|C:\\Miniconda"
                ]
              }
            }
          ]
        },
        {
          "NodeType": "HeaderNode",
          "Title": "Project Management",
          "Children": [
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Ant",
              "Version": "1.10.14"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Gradle",
              "Version": "8.11"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Maven",
              "Version": "3.9.9"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "sbt",
              "Version": "1.10.6"
            }
          ]
        },
        {
          "NodeType": "HeaderNode",
          "Title": "Tools",
          "Children": [
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "7zip",
              "Version": "24.09"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "aria2",
              "Version": "1.37.0"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "azcopy",
              "Version": "10.27.1"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Bazel",
              "Version": "8.0.0"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Bazelisk",
              "Version": "1.25.0"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Bicep",
              "Version": "0.32.4"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Cabal",
              "Version": "3.12.1.0"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "CMake",
              "Version": "3.31.2"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "CodeQL Action Bundle",
              "Version": "2.20.0"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Docker",
              "Version": "26.1.3"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Docker Compose v2",
              "Version": "2.27.1"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Docker-wincred",
              "Version": "0.8.2"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "ghc",
              "Version": "9.10.1"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Git",
              "Version": "2.47.1.windows.1"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "Git LFS",
              "Version": "3.6.0"
            },
            {
              "NodeType": "ToolVersionNode",
              "ToolName": "ImageMagick",
              "Versi [...]

2024-12-31 03:13 UTC, bearycool11 commented on images/windows/scripts/tests/WindowsFeatures.Tests.ps1
> -    $testCases = Get-WindowsUpdateStates | Sort-Object Title | ForEach-Object {
to start we going to take this

{
  "NodeType": "HeaderNode",
  "Title": "Windows Server 2025",
  "Children": [
    {
      "NodeType": "ToolVersionNode",
      "ToolName": "OS Version:",
      "Version": "10.0.26100 Build 2605"
    },
    {
      "NodeType": "ToolVersionNode",
      "ToolName": "Image Version:",
      "Version": "20241215.1.0"
    },
    {
      "NodeType": "HeaderNode",
      "Title": "Windows updates",
      "Children": [
        {
          "NodeType": "ToolVersionNode",
          "ToolName": "Update Title",
          "Version": "Some Update",
          "TimeCreated": "2024-12-30T12:34:56Z"
        },
        {
          "NodeType": "ToolVersionNode",
          "ToolName": "Another Update",
          "Version": "Another Update Version",
          "TimeCreated": "2024-12-30T12:34:56Z"
        }
      ]
    }
  ]
}

and combine it into the prototype.

2024-12-31 03:13 UTC, bearycool11 commented on images/windows/scripts/tests/WindowsFeatures.Tests.ps1
> -    $testCases = Get-WindowsUpdateStates | Sort-Object Title | ForEach-Object {
{
  "NodeType": "HeaderNode",
  "Title": "Windows Server 2025",
  "Children": [
    {
      "NodeType": "ToolVersionNode",
      "ToolName": "OS Version:",
      "Version": "10.0.26100 Build 2605"
    },
    {
      "NodeType": "ToolVersionNode",
      "ToolName": "Image Version:",
      "Version": "20241215.1.0"
    },
    {
      "NodeType": "HeaderNode",
      "Title": "Windows updates",
      "Children": [
        {
          "NodeType": "ToolVersionNode",
          "ToolName": "Update Title",
          "Version": "Some Update",
          "TimeCreated": "2024-12-30T12:34:56Z"
        },
        {
          "NodeType": "ToolVersionNode",
          "ToolName": "Another Update",
          "Version": "Another Update Version",
          "TimeCreated": "2024-12-30T12:34:56Z"
        }
      ]
    }
  ]
}

thank you CoPIlot for intergrating this by the way!
https://github.com/bearycool11/pmll_blockchain/blob/main/.devcontainer/internal.windows-2025.json

now turns into this repo's version of this.

2024-12-31 03:14 UTC, bearycool11 approved these changes

2024-12-31 03:35 UTC, bearycool11 requested changes
https://github.com/actions/runner-images/pull/11254

to fully intergrated the install helpers and runners

2024-12-31 03:53 UTC, AtOMiCNebula commented
@bearycool11, I don't think your issue is at all related to mine. My change is unrelated to devcontainer or the software-report.

2024-12-31 12:21 UTC, shamil-mubarakshin commented
Hey @AtOMiCNebula, thanks for contributing. We are aware of this issue and working on the same solution.
I am currently testing a [simpler approach](https://github.com/actions/runner-images/compare/main...shamil-mubarakshin:runner-images:troubleshoot-win-updates#diff-9d2baee2ecf6fb652185a4495daea7ff9fc4ec18914106f30d53d0804cbb5116R458) to skipping failed updates that succeeded later, but due to sporadic nature of this error I am rarely hitting it with some debug code so it takes time

2024-12-31 17:10 UTC, AtOMiCNebula commented
Hey @shamil-mubarakshin, thanks for the follow-up. Unfortunately for me, I've been hitting this issue constantly. 😦 Happy for your team to land your own fix for this, but this worked well to unblock me in my private testing, and I felt it was pretty safe, so I wanted to offer it up as an option.

Some additional changes I made to build with (that might help you hit it more consistently) are using the `Standard_D8ds_v5` SKU in `East US 2`, and also I bumped the image to the Gen2 equivalent (`2025-Datacenter-g2`). Not sure how far that'll get you, but I figured it can't hurt. 😄

2025-03-13 19:42 UTC, subir0071 commented
Closing this as a separate PR has already been merged

2025-03-13 19:42 UTC, closed without merging