[Ubuntu] do not add homebrew to $PATH
actions/runner-images pull request #6240
Opened 2022-09-14 15:17 UTC by mikhailkoliada

# Description

So it does not conflict with the canonical-provided software and toolchain in particular.

#### Related issue: n/a

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

2022-09-16 07:35 UTC, al-cheb submitted a review, later dismissed

2022-09-17 06:18 UTC, padel284 requested changes
@padel

2022-09-22 15:24 UTC, miketimofeev approved these changes

2022-09-22 15:54 UTC, maxim-lobanov approved these changes

2022-09-22 16:07 UTC, ddobranic approved these changes

2022-09-22 16:07 UTC, merged