Add Python to $PATH
actions/runner-images pull request #6518
Opened 2022-11-04 13:40 UTC by igorboskovic3

# Description
New tool, Bug fixing, or Improvement?  
Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.  
**For new tools, please provide total size and installation time.**

#### Related issue:

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

This is fix for https://github.com/actions/runner-images/issues/6507

2022-11-04 13:43 UTC, al-cheb commented on images/macos/provision/configuration/environment/bashrc
> +export PATH=/Library/Frameworks/Python.framework/Versions/Current/bin:$PATH
nitpick: move this line to the PATH section between 16..20 lines.

2022-11-04 22:53 UTC, khaledalam173 requested changes
New

2022-11-06 10:26 UTC, mikhailkoliada commented
/azp run macos1015,macos11,macos12

2022-11-08 11:28 UTC, al-cheb approved these changes

2022-11-08 11:30 UTC, merged

2022-11-17 03:32 UTC, khaledalam173 reviewed
#