[Windows] Update LLVM version to 15
actions/runner-images pull request #6838
Opened 2022-12-26 10:04 UTC by Alexey-Ayupov

# Description
Update LLVM version to 15

#### Related issue:
#6803

## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

2022-12-26 10:05 UTC, erik-bershel approved these changes

2022-12-26 10:13 UTC, mikhailkoliada commented
/azp run windows2019,windows2022

2022-12-29 20:29 UTC, JeffRohr1111 requested changes
No

2023-01-03 13:27 UTC, axljoker03 submitted a review, later dismissed

2023-01-04 10:09 UTC, mikhailkoliada commented
/azp run windows2019,windows2022

2023-01-04 14:36 UTC, mikhailkoliada approved these changes

2023-01-04 17:57 UTC, merged